// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/proto/simple.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionStatus_Status int32

const (
	TransactionStatus_PENDING   TransactionStatus_Status = 0
	TransactionStatus_CONFIRMED TransactionStatus_Status = 1
	TransactionStatus_FAILED    TransactionStatus_Status = 2
	TransactionStatus_REJECTED  TransactionStatus_Status = 3
)

// Enum value maps for TransactionStatus_Status.
var (
	TransactionStatus_Status_name = map[int32]string{
		0: "PENDING",
		1: "CONFIRMED",
		2: "FAILED",
		3: "REJECTED",
	}
	TransactionStatus_Status_value = map[string]int32{
		"PENDING":   0,
		"CONFIRMED": 1,
		"FAILED":    2,
		"REJECTED":  3,
	}
)

func (x TransactionStatus_Status) Enum() *TransactionStatus_Status {
	p := new(TransactionStatus_Status)
	*p = x
	return p
}

func (x TransactionStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_simple_proto_enumTypes[0].Descriptor()
}

func (TransactionStatus_Status) Type() protoreflect.EnumType {
	return &file_api_proto_simple_proto_enumTypes[0]
}

func (x TransactionStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus_Status.Descriptor instead.
func (TransactionStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{1, 0}
}

type NodeHealth_HealthStatus int32

const (
	NodeHealth_HEALTHY   NodeHealth_HealthStatus = 0
	NodeHealth_DEGRADED  NodeHealth_HealthStatus = 1
	NodeHealth_UNHEALTHY NodeHealth_HealthStatus = 2
)

// Enum value maps for NodeHealth_HealthStatus.
var (
	NodeHealth_HealthStatus_name = map[int32]string{
		0: "HEALTHY",
		1: "DEGRADED",
		2: "UNHEALTHY",
	}
	NodeHealth_HealthStatus_value = map[string]int32{
		"HEALTHY":   0,
		"DEGRADED":  1,
		"UNHEALTHY": 2,
	}
)

func (x NodeHealth_HealthStatus) Enum() *NodeHealth_HealthStatus {
	p := new(NodeHealth_HealthStatus)
	*p = x
	return p
}

func (x NodeHealth_HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeHealth_HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_simple_proto_enumTypes[1].Descriptor()
}

func (NodeHealth_HealthStatus) Type() protoreflect.EnumType {
	return &file_api_proto_simple_proto_enumTypes[1]
}

func (x NodeHealth_HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeHealth_HealthStatus.Descriptor instead.
func (NodeHealth_HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{9, 0}
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee           float64                `protobuf:"fixed64,5,opt,name=fee,proto3" json:"fee,omitempty"`
	Data          string                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Signature     string                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BlockHeight   uint64                 `protobuf:"varint,9,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Status        *TransactionStatus     `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_api_proto_simple_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Transaction) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Transaction) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Transaction) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Transaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Transaction) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *Transaction) GetStatus() *TransactionStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type TransactionStatus struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        TransactionStatus_Status `protobuf:"varint,1,opt,name=status,proto3,enum=diamante.api.TransactionStatus_Status" json:"status,omitempty"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Confirmations uint64                   `protobuf:"varint,3,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	ConfirmedAt   *timestamppb.Timestamp   `protobuf:"bytes,4,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionStatus) Reset() {
	*x = TransactionStatus{}
	mi := &file_api_proto_simple_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionStatus) ProtoMessage() {}

func (x *TransactionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionStatus.ProtoReflect.Descriptor instead.
func (*TransactionStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionStatus) GetStatus() TransactionStatus_Status {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_PENDING
}

func (x *TransactionStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransactionStatus) GetConfirmations() uint64 {
	if x != nil {
		return x.Confirmations
	}
	return 0
}

func (x *TransactionStatus) GetConfirmedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConfirmedAt
	}
	return nil
}

type Block struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Height           uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	PreviousHash     string                 `protobuf:"bytes,3,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	MerkleRoot       string                 `protobuf:"bytes,4,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	Timestamp        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Validator        string                 `protobuf:"bytes,6,opt,name=validator,proto3" json:"validator,omitempty"`
	Transactions     []*Transaction         `protobuf:"bytes,7,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Signature        string                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	Size             uint64                 `protobuf:"varint,9,opt,name=size,proto3" json:"size,omitempty"`
	TransactionCount uint64                 `protobuf:"varint,10,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_api_proto_simple_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{2}
}

func (x *Block) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Block) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Block) GetPreviousHash() string {
	if x != nil {
		return x.PreviousHash
	}
	return ""
}

func (x *Block) GetMerkleRoot() string {
	if x != nil {
		return x.MerkleRoot
	}
	return ""
}

func (x *Block) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Block) GetValidator() string {
	if x != nil {
		return x.Validator
	}
	return ""
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Block) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Block) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Block) GetTransactionCount() uint64 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Nonce         uint64                 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_api_proto_simple_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{3}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Account) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Account) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type AccountBalance struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AvailableBalance float64                `protobuf:"fixed64,2,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	PendingBalance   float64                `protobuf:"fixed64,3,opt,name=pending_balance,json=pendingBalance,proto3" json:"pending_balance,omitempty"`
	TotalBalance     float64                `protobuf:"fixed64,4,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	LastUpdated      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AccountBalance) Reset() {
	*x = AccountBalance{}
	mi := &file_api_proto_simple_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountBalance) ProtoMessage() {}

func (x *AccountBalance) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountBalance.ProtoReflect.Descriptor instead.
func (*AccountBalance) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{4}
}

func (x *AccountBalance) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountBalance) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *AccountBalance) GetPendingBalance() float64 {
	if x != nil {
		return x.PendingBalance
	}
	return 0
}

func (x *AccountBalance) GetTotalBalance() float64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

func (x *AccountBalance) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_api_proto_simple_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{5}
}

func (x *Wallet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wallet) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Wallet) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Wallet) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Wallet) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type Contract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Abi           string                 `protobuf:"bytes,4,opt,name=abi,proto3" json:"abi,omitempty"`
	Runtime       string                 `protobuf:"bytes,5,opt,name=runtime,proto3" json:"runtime,omitempty"` // "wasm", "evm", "native"
	DeployedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deployed_at,json=deployedAt,proto3" json:"deployed_at,omitempty"`
	Version       string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contract) Reset() {
	*x = Contract{}
	mi := &file_api_proto_simple_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contract) ProtoMessage() {}

func (x *Contract) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contract.ProtoReflect.Descriptor instead.
func (*Contract) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{6}
}

func (x *Contract) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Contract) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Contract) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Contract) GetAbi() string {
	if x != nil {
		return x.Abi
	}
	return ""
}

func (x *Contract) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *Contract) GetDeployedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeployedAt
	}
	return nil
}

func (x *Contract) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Contract) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type NetworkInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NetworkId         string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	ChainId           string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	LatestBlockHeight uint64                 `protobuf:"varint,3,opt,name=latest_block_height,json=latestBlockHeight,proto3" json:"latest_block_height,omitempty"`
	TotalTransactions uint64                 `protobuf:"varint,4,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	PeerCount         uint32                 `protobuf:"varint,5,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	Version           string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	StartedAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NetworkInfo) Reset() {
	*x = NetworkInfo{}
	mi := &file_api_proto_simple_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfo) ProtoMessage() {}

func (x *NetworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfo.ProtoReflect.Descriptor instead.
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkInfo) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *NetworkInfo) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *NetworkInfo) GetLatestBlockHeight() uint64 {
	if x != nil {
		return x.LatestBlockHeight
	}
	return 0
}

func (x *NetworkInfo) GetTotalTransactions() uint64 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *NetworkInfo) GetPeerCount() uint32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

func (x *NetworkInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NetworkInfo) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	LatestBlock   uint64                 `protobuf:"varint,4,opt,name=latest_block,json=latestBlock,proto3" json:"latest_block,omitempty"`
	IsValidator   bool                   `protobuf:"varint,5,opt,name=is_validator,json=isValidator,proto3" json:"is_validator,omitempty"`
	ConnectedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_api_proto_simple_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{8}
}

func (x *Peer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Peer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Peer) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Peer) GetLatestBlock() uint64 {
	if x != nil {
		return x.LatestBlock
	}
	return 0
}

func (x *Peer) GetIsValidator() bool {
	if x != nil {
		return x.IsValidator
	}
	return false
}

func (x *Peer) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

type NodeHealth struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	Status            NodeHealth_HealthStatus `protobuf:"varint,1,opt,name=status,proto3,enum=diamante.api.NodeHealth_HealthStatus" json:"status,omitempty"`
	Message           string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CpuUsage          float64                 `protobuf:"fixed64,3,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage       float64                 `protobuf:"fixed64,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	DiskUsage         float64                 `protobuf:"fixed64,5,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	ActiveConnections uint32                  `protobuf:"varint,6,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	LastCheck         *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeHealth) Reset() {
	*x = NodeHealth{}
	mi := &file_api_proto_simple_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHealth) ProtoMessage() {}

func (x *NodeHealth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHealth.ProtoReflect.Descriptor instead.
func (*NodeHealth) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{9}
}

func (x *NodeHealth) GetStatus() NodeHealth_HealthStatus {
	if x != nil {
		return x.Status
	}
	return NodeHealth_HEALTHY
}

func (x *NodeHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NodeHealth) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *NodeHealth) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *NodeHealth) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *NodeHealth) GetActiveConnections() uint32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *NodeHealth) GetLastCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheck
	}
	return nil
}

type ConsensusInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConsensusType     string                 `protobuf:"bytes,1,opt,name=consensus_type,json=consensusType,proto3" json:"consensus_type,omitempty"`
	CurrentRound      uint64                 `protobuf:"varint,2,opt,name=current_round,json=currentRound,proto3" json:"current_round,omitempty"`
	CurrentStep       uint64                 `protobuf:"varint,3,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	CurrentProposer   string                 `protobuf:"bytes,4,opt,name=current_proposer,json=currentProposer,proto3" json:"current_proposer,omitempty"`
	ValidatorCount    uint32                 `protobuf:"varint,5,opt,name=validator_count,json=validatorCount,proto3" json:"validator_count,omitempty"`
	ParticipationRate float64                `protobuf:"fixed64,6,opt,name=participation_rate,json=participationRate,proto3" json:"participation_rate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConsensusInfo) Reset() {
	*x = ConsensusInfo{}
	mi := &file_api_proto_simple_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusInfo) ProtoMessage() {}

func (x *ConsensusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusInfo.ProtoReflect.Descriptor instead.
func (*ConsensusInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{10}
}

func (x *ConsensusInfo) GetConsensusType() string {
	if x != nil {
		return x.ConsensusType
	}
	return ""
}

func (x *ConsensusInfo) GetCurrentRound() uint64 {
	if x != nil {
		return x.CurrentRound
	}
	return 0
}

func (x *ConsensusInfo) GetCurrentStep() uint64 {
	if x != nil {
		return x.CurrentStep
	}
	return 0
}

func (x *ConsensusInfo) GetCurrentProposer() string {
	if x != nil {
		return x.CurrentProposer
	}
	return ""
}

func (x *ConsensusInfo) GetValidatorCount() uint32 {
	if x != nil {
		return x.ValidatorCount
	}
	return 0
}

func (x *ConsensusInfo) GetParticipationRate() float64 {
	if x != nil {
		return x.ParticipationRate
	}
	return 0
}

type Validator struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey      string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Address        string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	VotingPower    float64                `protobuf:"fixed64,4,opt,name=voting_power,json=votingPower,proto3" json:"voting_power,omitempty"`
	IsActive       bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	BlocksProposed uint64                 `protobuf:"varint,6,opt,name=blocks_proposed,json=blocksProposed,proto3" json:"blocks_proposed,omitempty"`
	JoinedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Validator) Reset() {
	*x = Validator{}
	mi := &file_api_proto_simple_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Validator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validator) ProtoMessage() {}

func (x *Validator) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validator.ProtoReflect.Descriptor instead.
func (*Validator) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{11}
}

func (x *Validator) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Validator) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Validator) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Validator) GetVotingPower() float64 {
	if x != nil {
		return x.VotingPower
	}
	return 0
}

func (x *Validator) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Validator) GetBlocksProposed() uint64 {
	if x != nil {
		return x.BlocksProposed
	}
	return 0
}

func (x *Validator) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

type SubmitTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee           float64                `protobuf:"fixed64,4,opt,name=fee,proto3" json:"fee,omitempty"`
	Data          string                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Signature     string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTransactionRequest) Reset() {
	*x = SubmitTransactionRequest{}
	mi := &file_api_proto_simple_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionRequest) ProtoMessage() {}

func (x *SubmitTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionRequest.ProtoReflect.Descriptor instead.
func (*SubmitTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitTransactionRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SubmitTransactionRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SubmitTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SubmitTransactionRequest) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *SubmitTransactionRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *SubmitTransactionRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type SubmitTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        *TransactionStatus     `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTransactionResponse) Reset() {
	*x = SubmitTransactionResponse{}
	mi := &file_api_proto_simple_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionResponse) ProtoMessage() {}

func (x *SubmitTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionResponse.ProtoReflect.Descriptor instead.
func (*SubmitTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{13}
}

func (x *SubmitTransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *SubmitTransactionResponse) GetStatus() *TransactionStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SubmitTransactionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_api_proto_simple_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{14}
}

func (x *GetTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type GetTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsRequest) Reset() {
	*x = GetTransactionsRequest{}
	mi := &file_api_proto_simple_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsRequest) ProtoMessage() {}

func (x *GetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{15}
}

func (x *GetTransactionsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetTransactionsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTransactionsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetTransactionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	TotalCount    uint32                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsResponse) Reset() {
	*x = GetTransactionsResponse{}
	mi := &file_api_proto_simple_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsResponse) ProtoMessage() {}

func (x *GetTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{16}
}

func (x *GetTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetTransactionsResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetTransactionsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetTransactionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionStatusRequest) Reset() {
	*x = GetTransactionStatusRequest{}
	mi := &file_api_proto_simple_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionStatusRequest) ProtoMessage() {}

func (x *GetTransactionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{17}
}

func (x *GetTransactionStatusRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type GetBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockRequest) Reset() {
	*x = GetBlockRequest{}
	mi := &file_api_proto_simple_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRequest) ProtoMessage() {}

func (x *GetBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRequest.ProtoReflect.Descriptor instead.
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{18}
}

func (x *GetBlockRequest) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

type GetBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartHeight   uint64                 `protobuf:"varint,1,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	EndHeight     uint64                 `protobuf:"varint,2,opt,name=end_height,json=endHeight,proto3" json:"end_height,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlocksRequest) Reset() {
	*x = GetBlocksRequest{}
	mi := &file_api_proto_simple_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksRequest) ProtoMessage() {}

func (x *GetBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksRequest.ProtoReflect.Descriptor instead.
func (*GetBlocksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{19}
}

func (x *GetBlocksRequest) GetStartHeight() uint64 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

func (x *GetBlocksRequest) GetEndHeight() uint64 {
	if x != nil {
		return x.EndHeight
	}
	return 0
}

func (x *GetBlocksRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetBlocksRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*Block               `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	TotalCount    uint32                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlocksResponse) Reset() {
	*x = GetBlocksResponse{}
	mi := &file_api_proto_simple_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksResponse) ProtoMessage() {}

func (x *GetBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksResponse.ProtoReflect.Descriptor instead.
func (*GetBlocksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{20}
}

func (x *GetBlocksResponse) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *GetBlocksResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetBlocksResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_api_proto_simple_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{21}
}

func (x *GetAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccountBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountBalanceRequest) Reset() {
	*x = GetAccountBalanceRequest{}
	mi := &file_api_proto_simple_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountBalanceRequest) ProtoMessage() {}

func (x *GetAccountBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetAccountBalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{22}
}

func (x *GetAccountBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccountTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountTransactionsRequest) Reset() {
	*x = GetAccountTransactionsRequest{}
	mi := &file_api_proto_simple_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountTransactionsRequest) ProtoMessage() {}

func (x *GetAccountTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetAccountTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{23}
}

func (x *GetAccountTransactionsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetAccountTransactionsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAccountTransactionsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetAccountTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	TotalCount    uint32                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountTransactionsResponse) Reset() {
	*x = GetAccountTransactionsResponse{}
	mi := &file_api_proto_simple_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountTransactionsResponse) ProtoMessage() {}

func (x *GetAccountTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetAccountTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{24}
}

func (x *GetAccountTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetAccountTransactionsResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetAccountTransactionsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type CreateWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passphrase    string                 `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	mi := &file_api_proto_simple_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{25}
}

func (x *CreateWalletRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

func (x *CreateWalletRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_api_proto_simple_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{26}
}

func (x *GetWalletRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type SignTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WalletId        string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	TransactionData string                 `protobuf:"bytes,2,opt,name=transaction_data,json=transactionData,proto3" json:"transaction_data,omitempty"`
	Passphrase      string                 `protobuf:"bytes,3,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignTransactionRequest) Reset() {
	*x = SignTransactionRequest{}
	mi := &file_api_proto_simple_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionRequest) ProtoMessage() {}

func (x *SignTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionRequest.ProtoReflect.Descriptor instead.
func (*SignTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{27}
}

func (x *SignTransactionRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *SignTransactionRequest) GetTransactionData() string {
	if x != nil {
		return x.TransactionData
	}
	return ""
}

func (x *SignTransactionRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

type SignTransactionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SignedTransaction string                 `protobuf:"bytes,1,opt,name=signed_transaction,json=signedTransaction,proto3" json:"signed_transaction,omitempty"`
	Signature         string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignTransactionResponse) Reset() {
	*x = SignTransactionResponse{}
	mi := &file_api_proto_simple_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionResponse) ProtoMessage() {}

func (x *SignTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionResponse.ProtoReflect.Descriptor instead.
func (*SignTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{28}
}

func (x *SignTransactionResponse) GetSignedTransaction() string {
	if x != nil {
		return x.SignedTransaction
	}
	return ""
}

func (x *SignTransactionResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type DeployContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Abi           string                 `protobuf:"bytes,3,opt,name=abi,proto3" json:"abi,omitempty"`
	Runtime       string                 `protobuf:"bytes,4,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployContractRequest) Reset() {
	*x = DeployContractRequest{}
	mi := &file_api_proto_simple_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployContractRequest) ProtoMessage() {}

func (x *DeployContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployContractRequest.ProtoReflect.Descriptor instead.
func (*DeployContractRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{29}
}

func (x *DeployContractRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *DeployContractRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DeployContractRequest) GetAbi() string {
	if x != nil {
		return x.Abi
	}
	return ""
}

func (x *DeployContractRequest) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *DeployContractRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type DeployContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployContractResponse) Reset() {
	*x = DeployContractResponse{}
	mi := &file_api_proto_simple_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployContractResponse) ProtoMessage() {}

func (x *DeployContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployContractResponse.ProtoReflect.Descriptor instead.
func (*DeployContractResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{30}
}

func (x *DeployContractResponse) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *DeployContractResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *DeployContractResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type InvokeContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Parameters    []string               `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	Caller        string                 `protobuf:"bytes,4,opt,name=caller,proto3" json:"caller,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeContractRequest) Reset() {
	*x = InvokeContractRequest{}
	mi := &file_api_proto_simple_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeContractRequest) ProtoMessage() {}

func (x *InvokeContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeContractRequest.ProtoReflect.Descriptor instead.
func (*InvokeContractRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{31}
}

func (x *InvokeContractRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *InvokeContractRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InvokeContractRequest) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *InvokeContractRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

type InvokeContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	GasUsed       float64                `protobuf:"fixed64,3,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeContractResponse) Reset() {
	*x = InvokeContractResponse{}
	mi := &file_api_proto_simple_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeContractResponse) ProtoMessage() {}

func (x *InvokeContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeContractResponse.ProtoReflect.Descriptor instead.
func (*InvokeContractResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{32}
}

func (x *InvokeContractResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *InvokeContractResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *InvokeContractResponse) GetGasUsed() float64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

type GetContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractRequest) Reset() {
	*x = GetContractRequest{}
	mi := &file_api_proto_simple_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractRequest) ProtoMessage() {}

func (x *GetContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractRequest.ProtoReflect.Descriptor instead.
func (*GetContractRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{33}
}

func (x *GetContractRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

type GetPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	TotalCount    uint32                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersResponse) Reset() {
	*x = GetPeersResponse{}
	mi := &file_api_proto_simple_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersResponse) ProtoMessage() {}

func (x *GetPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersResponse.ProtoReflect.Descriptor instead.
func (*GetPeersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{34}
}

func (x *GetPeersResponse) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *GetPeersResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetValidatorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Validators    []*Validator           `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
	TotalCount    uint32                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValidatorsResponse) Reset() {
	*x = GetValidatorsResponse{}
	mi := &file_api_proto_simple_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValidatorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValidatorsResponse) ProtoMessage() {}

func (x *GetValidatorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simple_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValidatorsResponse.ProtoReflect.Descriptor instead.
func (*GetValidatorsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_simple_proto_rawDescGZIP(), []int{35}
}

func (x *GetValidatorsResponse) GetValidators() []*Validator {
	if x != nil {
		return x.Validators
	}
	return nil
}

func (x *GetValidatorsResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_api_proto_simple_proto protoreflect.FileDescriptor

const file_api_proto_simple_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/simple.proto\x12\fdiamante.api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb3\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x10\n" +
	"\x03fee\x18\x05 \x01(\x01R\x03fee\x12\x12\n" +
	"\x04data\x18\x06 \x01(\tR\x04data\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\fblock_height\x18\t \x01(\x04R\vblockHeight\x127\n" +
	"\x06status\x18\n" +
	" \x01(\v2\x1f.diamante.api.TransactionStatusR\x06status\"\x92\x02\n" +
	"\x11TransactionStatus\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.diamante.api.TransactionStatus.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\rconfirmations\x18\x03 \x01(\x04R\rconfirmations\x12=\n" +
	"\fconfirmed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vconfirmedAt\">\n" +
	"\x06Status\x12\v\n" +
	"\aPENDING\x10\x00\x12\r\n" +
	"\tCONFIRMED\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\x12\f\n" +
	"\bREJECTED\x10\x03\"\xeb\x02\n" +
	"\x05Block\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12#\n" +
	"\rprevious_hash\x18\x03 \x01(\tR\fpreviousHash\x12\x1f\n" +
	"\vmerkle_root\x18\x04 \x01(\tR\n" +
	"merkleRoot\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\tvalidator\x18\x06 \x01(\tR\tvalidator\x12=\n" +
	"\ftransactions\x18\a \x03(\v2\x19.diamante.api.TransactionR\ftransactions\x12\x1c\n" +
	"\tsignature\x18\b \x01(\tR\tsignature\x12\x12\n" +
	"\x04size\x18\t \x01(\x04R\x04size\x12+\n" +
	"\x11transaction_count\x18\n" +
	" \x01(\x04R\x10transactionCount\"\xde\x01\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\x04R\x05nonce\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe9\x01\n" +
	"\x0eAccountBalance\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12+\n" +
	"\x11available_balance\x18\x02 \x01(\x01R\x10availableBalance\x12'\n" +
	"\x0fpending_balance\x18\x03 \x01(\x01R\x0ependingBalance\x12#\n" +
	"\rtotal_balance\x18\x04 \x01(\x01R\ftotalBalance\x12=\n" +
	"\flast_updated\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"\xa9\x01\n" +
	"\x06Wallet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\"\xe4\x01\n" +
	"\bContract\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x10\n" +
	"\x03abi\x18\x04 \x01(\tR\x03abi\x12\x18\n" +
	"\aruntime\x18\x05 \x01(\tR\aruntime\x12;\n" +
	"\vdeployed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deployedAt\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\"\x9a\x02\n" +
	"\vNetworkInfo\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12.\n" +
	"\x13latest_block_height\x18\x03 \x01(\x04R\x11latestBlockHeight\x12-\n" +
	"\x12total_transactions\x18\x04 \x01(\x04R\x11totalTransactions\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x05 \x01(\rR\tpeerCount\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"\xcf\x01\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12!\n" +
	"\flatest_block\x18\x04 \x01(\x04R\vlatestBlock\x12!\n" +
	"\fis_validator\x18\x05 \x01(\bR\visValidator\x12=\n" +
	"\fconnected_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\"\xe8\x02\n" +
	"\n" +
	"NodeHealth\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.diamante.api.NodeHealth.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tcpu_usage\x18\x03 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\x01R\vmemoryUsage\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x05 \x01(\x01R\tdiskUsage\x12-\n" +
	"\x12active_connections\x18\x06 \x01(\rR\x11activeConnections\x129\n" +
	"\n" +
	"last_check\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tlastCheck\"8\n" +
	"\fHealthStatus\x12\v\n" +
	"\aHEALTHY\x10\x00\x12\f\n" +
	"\bDEGRADED\x10\x01\x12\r\n" +
	"\tUNHEALTHY\x10\x02\"\x81\x02\n" +
	"\rConsensusInfo\x12%\n" +
	"\x0econsensus_type\x18\x01 \x01(\tR\rconsensusType\x12#\n" +
	"\rcurrent_round\x18\x02 \x01(\x04R\fcurrentRound\x12!\n" +
	"\fcurrent_step\x18\x03 \x01(\x04R\vcurrentStep\x12)\n" +
	"\x10current_proposer\x18\x04 \x01(\tR\x0fcurrentProposer\x12'\n" +
	"\x0fvalidator_count\x18\x05 \x01(\rR\x0evalidatorCount\x12-\n" +
	"\x12participation_rate\x18\x06 \x01(\x01R\x11participationRate\"\xf6\x01\n" +
	"\tValidator\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12!\n" +
	"\fvoting_power\x18\x04 \x01(\x01R\vvotingPower\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12'\n" +
	"\x0fblocks_proposed\x18\x06 \x01(\x04R\x0eblocksProposed\x127\n" +
	"\tjoined_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\"\x9a\x01\n" +
	"\x18SubmitTransactionRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x10\n" +
	"\x03fee\x18\x04 \x01(\x01R\x03fee\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04data\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\"\x95\x01\n" +
	"\x19SubmitTransactionResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x127\n" +
	"\x06status\x18\x02 \x01(\v2\x1f.diamante.api.TransactionStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\">\n" +
	"\x15GetTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"x\n" +
	"\x16GetTransactionsRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x94\x01\n" +
	"\x17GetTransactionsResponse\x12=\n" +
	"\ftransactions\x18\x01 \x03(\v2\x19.diamante.api.TransactionR\ftransactions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\rR\n" +
	"totalCount\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"D\n" +
	"\x1bGetTransactionStatusRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\",\n" +
	"\x0fGetBlockRequest\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\"\x82\x01\n" +
	"\x10GetBlocksRequest\x12!\n" +
	"\fstart_height\x18\x01 \x01(\x04R\vstartHeight\x12\x1d\n" +
	"\n" +
	"end_height\x18\x02 \x01(\x04R\tendHeight\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\rR\x06offset\"|\n" +
	"\x11GetBlocksResponse\x12+\n" +
	"\x06blocks\x18\x01 \x03(\v2\x13.diamante.api.BlockR\x06blocks\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\rR\n" +
	"totalCount\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"2\n" +
	"\x11GetAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"9\n" +
	"\x18GetAccountBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"l\n" +
	"\x1dGetAccountTransactionsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\"\x9b\x01\n" +
	"\x1eGetAccountTransactionsResponse\x12=\n" +
	"\ftransactions\x18\x01 \x03(\v2\x19.diamante.api.TransactionR\ftransactions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\rR\n" +
	"totalCount\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\xbf\x01\n" +
	"\x13CreateWalletRequest\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x01 \x01(\tR\n" +
	"passphrase\x12K\n" +
	"\bmetadata\x18\x02 \x03(\v2/.diamante.api.CreateWalletRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x10GetWalletRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"\x80\x01\n" +
	"\x16SignTransactionRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12)\n" +
	"\x10transaction_data\x18\x02 \x01(\tR\x0ftransactionData\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x03 \x01(\tR\n" +
	"passphrase\"f\n" +
	"\x17SignTransactionResponse\x12-\n" +
	"\x12signed_transaction\x18\x01 \x01(\tR\x11signedTransaction\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\"\x81\x02\n" +
	"\x15DeployContractRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x10\n" +
	"\x03abi\x18\x03 \x01(\tR\x03abi\x12\x18\n" +
	"\aruntime\x18\x04 \x01(\tR\aruntime\x12S\n" +
	"\n" +
	"parameters\x18\x05 \x03(\v23.diamante.api.DeployContractRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"z\n" +
	"\x16DeployContractResponse\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\x88\x01\n" +
	"\x15InvokeContractRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x03(\tR\n" +
	"parameters\x12\x16\n" +
	"\x06caller\x18\x04 \x01(\tR\x06caller\"r\n" +
	"\x16InvokeContractResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x19\n" +
	"\bgas_used\x18\x03 \x01(\x01R\agasUsed\"5\n" +
	"\x12GetContractRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\"]\n" +
	"\x10GetPeersResponse\x12(\n" +
	"\x05peers\x18\x01 \x03(\v2\x12.diamante.api.PeerR\x05peers\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\rR\n" +
	"totalCount\"q\n" +
	"\x15GetValidatorsResponse\x127\n" +
	"\n" +
	"validators\x18\x01 \x03(\v2\x17.diamante.api.ValidatorR\n" +
	"validators\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\rR\n" +
	"totalCount2\xc8\r\n" +
	"\x15DiamanteBChainService\x12d\n" +
	"\x11SubmitTransaction\x12&.diamante.api.SubmitTransactionRequest\x1a'.diamante.api.SubmitTransactionResponse\x12P\n" +
	"\x0eGetTransaction\x12#.diamante.api.GetTransactionRequest\x1a\x19.diamante.api.Transaction\x12^\n" +
	"\x0fGetTransactions\x12$.diamante.api.GetTransactionsRequest\x1a%.diamante.api.GetTransactionsResponse\x12b\n" +
	"\x14GetTransactionStatus\x12).diamante.api.GetTransactionStatusRequest\x1a\x1f.diamante.api.TransactionStatus\x12>\n" +
	"\bGetBlock\x12\x1d.diamante.api.GetBlockRequest\x1a\x13.diamante.api.Block\x12L\n" +
	"\tGetBlocks\x12\x1e.diamante.api.GetBlocksRequest\x1a\x1f.diamante.api.GetBlocksResponse\x12=\n" +
	"\x0eGetLatestBlock\x12\x16.google.protobuf.Empty\x1a\x13.diamante.api.Block\x12D\n" +
	"\n" +
	"GetAccount\x12\x1f.diamante.api.GetAccountRequest\x1a\x15.diamante.api.Account\x12Y\n" +
	"\x11GetAccountBalance\x12&.diamante.api.GetAccountBalanceRequest\x1a\x1c.diamante.api.AccountBalance\x12s\n" +
	"\x16GetAccountTransactions\x12+.diamante.api.GetAccountTransactionsRequest\x1a,.diamante.api.GetAccountTransactionsResponse\x12G\n" +
	"\fCreateWallet\x12!.diamante.api.CreateWalletRequest\x1a\x14.diamante.api.Wallet\x12A\n" +
	"\tGetWallet\x12\x1e.diamante.api.GetWalletRequest\x1a\x14.diamante.api.Wallet\x12^\n" +
	"\x0fSignTransaction\x12$.diamante.api.SignTransactionRequest\x1a%.diamante.api.SignTransactionResponse\x12[\n" +
	"\x0eDeployContract\x12#.diamante.api.DeployContractRequest\x1a$.diamante.api.DeployContractResponse\x12[\n" +
	"\x0eInvokeContract\x12#.diamante.api.InvokeContractRequest\x1a$.diamante.api.InvokeContractResponse\x12G\n" +
	"\vGetContract\x12 .diamante.api.GetContractRequest\x1a\x16.diamante.api.Contract\x12C\n" +
	"\x0eGetNetworkInfo\x12\x16.google.protobuf.Empty\x1a\x19.diamante.api.NetworkInfo\x12B\n" +
	"\bGetPeers\x12\x16.google.protobuf.Empty\x1a\x1e.diamante.api.GetPeersResponse\x12A\n" +
	"\rGetNodeHealth\x12\x16.google.protobuf.Empty\x1a\x18.diamante.api.NodeHealth\x12G\n" +
	"\x10GetConsensusInfo\x12\x16.google.protobuf.Empty\x1a\x1b.diamante.api.ConsensusInfo\x12L\n" +
	"\rGetValidators\x12\x16.google.protobuf.Empty\x1a#.diamante.api.GetValidatorsResponseB\x14Z\x12diamante/api/protob\x06proto3"

var (
	file_api_proto_simple_proto_rawDescOnce sync.Once
	file_api_proto_simple_proto_rawDescData []byte
)

func file_api_proto_simple_proto_rawDescGZIP() []byte {
	file_api_proto_simple_proto_rawDescOnce.Do(func() {
		file_api_proto_simple_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_simple_proto_rawDesc), len(file_api_proto_simple_proto_rawDesc)))
	})
	return file_api_proto_simple_proto_rawDescData
}

var file_api_proto_simple_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_simple_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_api_proto_simple_proto_goTypes = []any{
	(TransactionStatus_Status)(0),          // 0: diamante.api.TransactionStatus.Status
	(NodeHealth_HealthStatus)(0),           // 1: diamante.api.NodeHealth.HealthStatus
	(*Transaction)(nil),                    // 2: diamante.api.Transaction
	(*TransactionStatus)(nil),              // 3: diamante.api.TransactionStatus
	(*Block)(nil),                          // 4: diamante.api.Block
	(*Account)(nil),                        // 5: diamante.api.Account
	(*AccountBalance)(nil),                 // 6: diamante.api.AccountBalance
	(*Wallet)(nil),                         // 7: diamante.api.Wallet
	(*Contract)(nil),                       // 8: diamante.api.Contract
	(*NetworkInfo)(nil),                    // 9: diamante.api.NetworkInfo
	(*Peer)(nil),                           // 10: diamante.api.Peer
	(*NodeHealth)(nil),                     // 11: diamante.api.NodeHealth
	(*ConsensusInfo)(nil),                  // 12: diamante.api.ConsensusInfo
	(*Validator)(nil),                      // 13: diamante.api.Validator
	(*SubmitTransactionRequest)(nil),       // 14: diamante.api.SubmitTransactionRequest
	(*SubmitTransactionResponse)(nil),      // 15: diamante.api.SubmitTransactionResponse
	(*GetTransactionRequest)(nil),          // 16: diamante.api.GetTransactionRequest
	(*GetTransactionsRequest)(nil),         // 17: diamante.api.GetTransactionsRequest
	(*GetTransactionsResponse)(nil),        // 18: diamante.api.GetTransactionsResponse
	(*GetTransactionStatusRequest)(nil),    // 19: diamante.api.GetTransactionStatusRequest
	(*GetBlockRequest)(nil),                // 20: diamante.api.GetBlockRequest
	(*GetBlocksRequest)(nil),               // 21: diamante.api.GetBlocksRequest
	(*GetBlocksResponse)(nil),              // 22: diamante.api.GetBlocksResponse
	(*GetAccountRequest)(nil),              // 23: diamante.api.GetAccountRequest
	(*GetAccountBalanceRequest)(nil),       // 24: diamante.api.GetAccountBalanceRequest
	(*GetAccountTransactionsRequest)(nil),  // 25: diamante.api.GetAccountTransactionsRequest
	(*GetAccountTransactionsResponse)(nil), // 26: diamante.api.GetAccountTransactionsResponse
	(*CreateWalletRequest)(nil),            // 27: diamante.api.CreateWalletRequest
	(*GetWalletRequest)(nil),               // 28: diamante.api.GetWalletRequest
	(*SignTransactionRequest)(nil),         // 29: diamante.api.SignTransactionRequest
	(*SignTransactionResponse)(nil),        // 30: diamante.api.SignTransactionResponse
	(*DeployContractRequest)(nil),          // 31: diamante.api.DeployContractRequest
	(*DeployContractResponse)(nil),         // 32: diamante.api.DeployContractResponse
	(*InvokeContractRequest)(nil),          // 33: diamante.api.InvokeContractRequest
	(*InvokeContractResponse)(nil),         // 34: diamante.api.InvokeContractResponse
	(*GetContractRequest)(nil),             // 35: diamante.api.GetContractRequest
	(*GetPeersResponse)(nil),               // 36: diamante.api.GetPeersResponse
	(*GetValidatorsResponse)(nil),          // 37: diamante.api.GetValidatorsResponse
	nil,                                    // 38: diamante.api.CreateWalletRequest.MetadataEntry
	nil,                                    // 39: diamante.api.DeployContractRequest.ParametersEntry
	(*timestamppb.Timestamp)(nil),          // 40: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 41: google.protobuf.Empty
}
var file_api_proto_simple_proto_depIdxs = []int32{
	40, // 0: diamante.api.Transaction.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 1: diamante.api.Transaction.status:type_name -> diamante.api.TransactionStatus
	0,  // 2: diamante.api.TransactionStatus.status:type_name -> diamante.api.TransactionStatus.Status
	40, // 3: diamante.api.TransactionStatus.confirmed_at:type_name -> google.protobuf.Timestamp
	40, // 4: diamante.api.Block.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 5: diamante.api.Block.transactions:type_name -> diamante.api.Transaction
	40, // 6: diamante.api.Account.created_at:type_name -> google.protobuf.Timestamp
	40, // 7: diamante.api.Account.updated_at:type_name -> google.protobuf.Timestamp
	40, // 8: diamante.api.AccountBalance.last_updated:type_name -> google.protobuf.Timestamp
	40, // 9: diamante.api.Wallet.created_at:type_name -> google.protobuf.Timestamp
	40, // 10: diamante.api.Contract.deployed_at:type_name -> google.protobuf.Timestamp
	40, // 11: diamante.api.NetworkInfo.started_at:type_name -> google.protobuf.Timestamp
	40, // 12: diamante.api.Peer.connected_at:type_name -> google.protobuf.Timestamp
	1,  // 13: diamante.api.NodeHealth.status:type_name -> diamante.api.NodeHealth.HealthStatus
	40, // 14: diamante.api.NodeHealth.last_check:type_name -> google.protobuf.Timestamp
	40, // 15: diamante.api.Validator.joined_at:type_name -> google.protobuf.Timestamp
	3,  // 16: diamante.api.SubmitTransactionResponse.status:type_name -> diamante.api.TransactionStatus
	2,  // 17: diamante.api.GetTransactionsResponse.transactions:type_name -> diamante.api.Transaction
	4,  // 18: diamante.api.GetBlocksResponse.blocks:type_name -> diamante.api.Block
	2,  // 19: diamante.api.GetAccountTransactionsResponse.transactions:type_name -> diamante.api.Transaction
	38, // 20: diamante.api.CreateWalletRequest.metadata:type_name -> diamante.api.CreateWalletRequest.MetadataEntry
	39, // 21: diamante.api.DeployContractRequest.parameters:type_name -> diamante.api.DeployContractRequest.ParametersEntry
	10, // 22: diamante.api.GetPeersResponse.peers:type_name -> diamante.api.Peer
	13, // 23: diamante.api.GetValidatorsResponse.validators:type_name -> diamante.api.Validator
	14, // 24: diamante.api.DiamanteBChainService.SubmitTransaction:input_type -> diamante.api.SubmitTransactionRequest
	16, // 25: diamante.api.DiamanteBChainService.GetTransaction:input_type -> diamante.api.GetTransactionRequest
	17, // 26: diamante.api.DiamanteBChainService.GetTransactions:input_type -> diamante.api.GetTransactionsRequest
	19, // 27: diamante.api.DiamanteBChainService.GetTransactionStatus:input_type -> diamante.api.GetTransactionStatusRequest
	20, // 28: diamante.api.DiamanteBChainService.GetBlock:input_type -> diamante.api.GetBlockRequest
	21, // 29: diamante.api.DiamanteBChainService.GetBlocks:input_type -> diamante.api.GetBlocksRequest
	41, // 30: diamante.api.DiamanteBChainService.GetLatestBlock:input_type -> google.protobuf.Empty
	23, // 31: diamante.api.DiamanteBChainService.GetAccount:input_type -> diamante.api.GetAccountRequest
	24, // 32: diamante.api.DiamanteBChainService.GetAccountBalance:input_type -> diamante.api.GetAccountBalanceRequest
	25, // 33: diamante.api.DiamanteBChainService.GetAccountTransactions:input_type -> diamante.api.GetAccountTransactionsRequest
	27, // 34: diamante.api.DiamanteBChainService.CreateWallet:input_type -> diamante.api.CreateWalletRequest
	28, // 35: diamante.api.DiamanteBChainService.GetWallet:input_type -> diamante.api.GetWalletRequest
	29, // 36: diamante.api.DiamanteBChainService.SignTransaction:input_type -> diamante.api.SignTransactionRequest
	31, // 37: diamante.api.DiamanteBChainService.DeployContract:input_type -> diamante.api.DeployContractRequest
	33, // 38: diamante.api.DiamanteBChainService.InvokeContract:input_type -> diamante.api.InvokeContractRequest
	35, // 39: diamante.api.DiamanteBChainService.GetContract:input_type -> diamante.api.GetContractRequest
	41, // 40: diamante.api.DiamanteBChainService.GetNetworkInfo:input_type -> google.protobuf.Empty
	41, // 41: diamante.api.DiamanteBChainService.GetPeers:input_type -> google.protobuf.Empty
	41, // 42: diamante.api.DiamanteBChainService.GetNodeHealth:input_type -> google.protobuf.Empty
	41, // 43: diamante.api.DiamanteBChainService.GetConsensusInfo:input_type -> google.protobuf.Empty
	41, // 44: diamante.api.DiamanteBChainService.GetValidators:input_type -> google.protobuf.Empty
	15, // 45: diamante.api.DiamanteBChainService.SubmitTransaction:output_type -> diamante.api.SubmitTransactionResponse
	2,  // 46: diamante.api.DiamanteBChainService.GetTransaction:output_type -> diamante.api.Transaction
	18, // 47: diamante.api.DiamanteBChainService.GetTransactions:output_type -> diamante.api.GetTransactionsResponse
	3,  // 48: diamante.api.DiamanteBChainService.GetTransactionStatus:output_type -> diamante.api.TransactionStatus
	4,  // 49: diamante.api.DiamanteBChainService.GetBlock:output_type -> diamante.api.Block
	22, // 50: diamante.api.DiamanteBChainService.GetBlocks:output_type -> diamante.api.GetBlocksResponse
	4,  // 51: diamante.api.DiamanteBChainService.GetLatestBlock:output_type -> diamante.api.Block
	5,  // 52: diamante.api.DiamanteBChainService.GetAccount:output_type -> diamante.api.Account
	6,  // 53: diamante.api.DiamanteBChainService.GetAccountBalance:output_type -> diamante.api.AccountBalance
	26, // 54: diamante.api.DiamanteBChainService.GetAccountTransactions:output_type -> diamante.api.GetAccountTransactionsResponse
	7,  // 55: diamante.api.DiamanteBChainService.CreateWallet:output_type -> diamante.api.Wallet
	7,  // 56: diamante.api.DiamanteBChainService.GetWallet:output_type -> diamante.api.Wallet
	30, // 57: diamante.api.DiamanteBChainService.SignTransaction:output_type -> diamante.api.SignTransactionResponse
	32, // 58: diamante.api.DiamanteBChainService.DeployContract:output_type -> diamante.api.DeployContractResponse
	34, // 59: diamante.api.DiamanteBChainService.InvokeContract:output_type -> diamante.api.InvokeContractResponse
	8,  // 60: diamante.api.DiamanteBChainService.GetContract:output_type -> diamante.api.Contract
	9,  // 61: diamante.api.DiamanteBChainService.GetNetworkInfo:output_type -> diamante.api.NetworkInfo
	36, // 62: diamante.api.DiamanteBChainService.GetPeers:output_type -> diamante.api.GetPeersResponse
	11, // 63: diamante.api.DiamanteBChainService.GetNodeHealth:output_type -> diamante.api.NodeHealth
	12, // 64: diamante.api.DiamanteBChainService.GetConsensusInfo:output_type -> diamante.api.ConsensusInfo
	37, // 65: diamante.api.DiamanteBChainService.GetValidators:output_type -> diamante.api.GetValidatorsResponse
	45, // [45:66] is the sub-list for method output_type
	24, // [24:45] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_api_proto_simple_proto_init() }
func file_api_proto_simple_proto_init() {
	if File_api_proto_simple_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_simple_proto_rawDesc), len(file_api_proto_simple_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_simple_proto_goTypes,
		DependencyIndexes: file_api_proto_simple_proto_depIdxs,
		EnumInfos:         file_api_proto_simple_proto_enumTypes,
		MessageInfos:      file_api_proto_simple_proto_msgTypes,
	}.Build()
	File_api_proto_simple_proto = out.File
	file_api_proto_simple_proto_goTypes = nil
	file_api_proto_simple_proto_depIdxs = nil
}
