// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/simple.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiamanteBChainService_SubmitTransaction_FullMethodName      = "/diamante.api.DiamanteBChainService/SubmitTransaction"
	DiamanteBChainService_GetTransaction_FullMethodName         = "/diamante.api.DiamanteBChainService/GetTransaction"
	DiamanteBChainService_GetTransactions_FullMethodName        = "/diamante.api.DiamanteBChainService/GetTransactions"
	DiamanteBChainService_GetTransactionStatus_FullMethodName   = "/diamante.api.DiamanteBChainService/GetTransactionStatus"
	DiamanteBChainService_GetBlock_FullMethodName               = "/diamante.api.DiamanteBChainService/GetBlock"
	DiamanteBChainService_GetBlocks_FullMethodName              = "/diamante.api.DiamanteBChainService/GetBlocks"
	DiamanteBChainService_GetLatestBlock_FullMethodName         = "/diamante.api.DiamanteBChainService/GetLatestBlock"
	DiamanteBChainService_GetAccount_FullMethodName             = "/diamante.api.DiamanteBChainService/GetAccount"
	DiamanteBChainService_GetAccountBalance_FullMethodName      = "/diamante.api.DiamanteBChainService/GetAccountBalance"
	DiamanteBChainService_GetAccountTransactions_FullMethodName = "/diamante.api.DiamanteBChainService/GetAccountTransactions"
	DiamanteBChainService_CreateWallet_FullMethodName           = "/diamante.api.DiamanteBChainService/CreateWallet"
	DiamanteBChainService_GetWallet_FullMethodName              = "/diamante.api.DiamanteBChainService/GetWallet"
	DiamanteBChainService_SignTransaction_FullMethodName        = "/diamante.api.DiamanteBChainService/SignTransaction"
	DiamanteBChainService_DeployContract_FullMethodName         = "/diamante.api.DiamanteBChainService/DeployContract"
	DiamanteBChainService_InvokeContract_FullMethodName         = "/diamante.api.DiamanteBChainService/InvokeContract"
	DiamanteBChainService_GetContract_FullMethodName            = "/diamante.api.DiamanteBChainService/GetContract"
	DiamanteBChainService_GetNetworkInfo_FullMethodName         = "/diamante.api.DiamanteBChainService/GetNetworkInfo"
	DiamanteBChainService_GetPeers_FullMethodName               = "/diamante.api.DiamanteBChainService/GetPeers"
	DiamanteBChainService_GetNodeHealth_FullMethodName          = "/diamante.api.DiamanteBChainService/GetNodeHealth"
	DiamanteBChainService_GetConsensusInfo_FullMethodName       = "/diamante.api.DiamanteBChainService/GetConsensusInfo"
	DiamanteBChainService_GetValidators_FullMethodName          = "/diamante.api.DiamanteBChainService/GetValidators"
)

// DiamanteBChainServiceClient is the client API for DiamanteBChainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Diamante gRPC API service
type DiamanteBChainServiceClient interface {
	// Transaction operations
	SubmitTransaction(ctx context.Context, in *SubmitTransactionRequest, opts ...grpc.CallOption) (*SubmitTransactionResponse, error)
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*Transaction, error)
	GetTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (*GetTransactionsResponse, error)
	GetTransactionStatus(ctx context.Context, in *GetTransactionStatusRequest, opts ...grpc.CallOption) (*TransactionStatus, error)
	// Block operations
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*Block, error)
	GetBlocks(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (*GetBlocksResponse, error)
	GetLatestBlock(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Block, error)
	// Account operations
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error)
	GetAccountBalance(ctx context.Context, in *GetAccountBalanceRequest, opts ...grpc.CallOption) (*AccountBalance, error)
	GetAccountTransactions(ctx context.Context, in *GetAccountTransactionsRequest, opts ...grpc.CallOption) (*GetAccountTransactionsResponse, error)
	// Wallet operations
	CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*Wallet, error)
	GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*Wallet, error)
	SignTransaction(ctx context.Context, in *SignTransactionRequest, opts ...grpc.CallOption) (*SignTransactionResponse, error)
	// Smart Contract operations
	DeployContract(ctx context.Context, in *DeployContractRequest, opts ...grpc.CallOption) (*DeployContractResponse, error)
	InvokeContract(ctx context.Context, in *InvokeContractRequest, opts ...grpc.CallOption) (*InvokeContractResponse, error)
	GetContract(ctx context.Context, in *GetContractRequest, opts ...grpc.CallOption) (*Contract, error)
	// Network operations
	GetNetworkInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NetworkInfo, error)
	GetPeers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPeersResponse, error)
	GetNodeHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodeHealth, error)
	// Consensus operations
	GetConsensusInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ConsensusInfo, error)
	GetValidators(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetValidatorsResponse, error)
}

type diamanteBChainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiamanteBChainServiceClient(cc grpc.ClientConnInterface) DiamanteBChainServiceClient {
	return &diamanteBChainServiceClient{cc}
}

func (c *diamanteBChainServiceClient) SubmitTransaction(ctx context.Context, in *SubmitTransactionRequest, opts ...grpc.CallOption) (*SubmitTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitTransactionResponse)
	err := c.cc.Invoke(ctx, DiamanteBChainService_SubmitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diamanteBChainServiceClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*Transaction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transaction)
	err := c.cc.Invoke(ctx, DiamanteBChainService_GetTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diamanteBChainServiceClient) GetTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (*GetTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionsResponse)
	err := c.cc.Invoke(ctx, DiamanteBChainService_GetTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diamanteBChainServiceClient) GetTransactionStatus(ctx context.Context, in *GetTransactionStatusRequest, opts ...grpc.CallOption) (*TransactionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionStatus)
	err := c.cc.Invoke(ctx, DiamanteBChainService_GetTransactionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diamanteBChainServiceClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*Block, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Block)
	err := c.cc.Invoke(ctx, DiamanteBChainService_GetBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diamanteBChainServiceClient) GetBlocks(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (*GetBlocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlocksResponse)
	err := c.cc.Invoke(ctx, DiamanteBChainService_GetBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diamanteBChainServiceClient) GetLatestBlock(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Block, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Block)
	err := c.cc.Invoke(ctx, DiamanteBChainService_GetLatestBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diamanteBChainServiceClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Account)
	err := c.cc.Invoke(ctx, DiamanteBChainService_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diamanteBChainServiceClient) GetAccountBalance(ctx context.Context, in *GetAccountBalanceRequest, opts ...grpc.CallOption) (*AccountBalance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountBalance)
	err := c.cc.Invoke(ctx, DiamanteBChainService_GetAccountBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diamanteBChainServiceClient) GetAccountTransactions(ctx context.Context, in *GetAccountTransactionsRequest, opts ...grpc.CallOption) (*GetAccountTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountTransactionsResponse)
	err := c.cc.Invoke(ctx, DiamanteBChainService_GetAccountTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diamanteBChainServiceClient) CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*Wallet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Wallet)
	err := c.cc.Invoke(ctx, DiamanteBChainService_CreateWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diamanteBChainServiceClient) GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*Wallet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Wallet)
	err := c.cc.Invoke(ctx, DiamanteBChainService_GetWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diamanteBChainServiceClient) SignTransaction(ctx context.Context, in *SignTransactionRequest, opts ...grpc.CallOption) (*SignTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignTransactionResponse)
	err := c.cc.Invoke(ctx, DiamanteBChainService_SignTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diamanteBChainServiceClient) DeployContract(ctx context.Context, in *DeployContractRequest, opts ...grpc.CallOption) (*DeployContractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployContractResponse)
	err := c.cc.Invoke(ctx, DiamanteBChainService_DeployContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diamanteBChainServiceClient) InvokeContract(ctx context.Context, in *InvokeContractRequest, opts ...grpc.CallOption) (*InvokeContractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeContractResponse)
	err := c.cc.Invoke(ctx, DiamanteBChainService_InvokeContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diamanteBChainServiceClient) GetContract(ctx context.Context, in *GetContractRequest, opts ...grpc.CallOption) (*Contract, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Contract)
	err := c.cc.Invoke(ctx, DiamanteBChainService_GetContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diamanteBChainServiceClient) GetNetworkInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NetworkInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkInfo)
	err := c.cc.Invoke(ctx, DiamanteBChainService_GetNetworkInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diamanteBChainServiceClient) GetPeers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPeersResponse)
	err := c.cc.Invoke(ctx, DiamanteBChainService_GetPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diamanteBChainServiceClient) GetNodeHealth(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodeHealth, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeHealth)
	err := c.cc.Invoke(ctx, DiamanteBChainService_GetNodeHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diamanteBChainServiceClient) GetConsensusInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ConsensusInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsensusInfo)
	err := c.cc.Invoke(ctx, DiamanteBChainService_GetConsensusInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diamanteBChainServiceClient) GetValidators(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetValidatorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetValidatorsResponse)
	err := c.cc.Invoke(ctx, DiamanteBChainService_GetValidators_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiamanteBChainServiceServer is the server API for DiamanteBChainService service.
// All implementations must embed UnimplementedDiamanteBChainServiceServer
// for forward compatibility.
//
// Diamante gRPC API service
type DiamanteBChainServiceServer interface {
	// Transaction operations
	SubmitTransaction(context.Context, *SubmitTransactionRequest) (*SubmitTransactionResponse, error)
	GetTransaction(context.Context, *GetTransactionRequest) (*Transaction, error)
	GetTransactions(context.Context, *GetTransactionsRequest) (*GetTransactionsResponse, error)
	GetTransactionStatus(context.Context, *GetTransactionStatusRequest) (*TransactionStatus, error)
	// Block operations
	GetBlock(context.Context, *GetBlockRequest) (*Block, error)
	GetBlocks(context.Context, *GetBlocksRequest) (*GetBlocksResponse, error)
	GetLatestBlock(context.Context, *emptypb.Empty) (*Block, error)
	// Account operations
	GetAccount(context.Context, *GetAccountRequest) (*Account, error)
	GetAccountBalance(context.Context, *GetAccountBalanceRequest) (*AccountBalance, error)
	GetAccountTransactions(context.Context, *GetAccountTransactionsRequest) (*GetAccountTransactionsResponse, error)
	// Wallet operations
	CreateWallet(context.Context, *CreateWalletRequest) (*Wallet, error)
	GetWallet(context.Context, *GetWalletRequest) (*Wallet, error)
	SignTransaction(context.Context, *SignTransactionRequest) (*SignTransactionResponse, error)
	// Smart Contract operations
	DeployContract(context.Context, *DeployContractRequest) (*DeployContractResponse, error)
	InvokeContract(context.Context, *InvokeContractRequest) (*InvokeContractResponse, error)
	GetContract(context.Context, *GetContractRequest) (*Contract, error)
	// Network operations
	GetNetworkInfo(context.Context, *emptypb.Empty) (*NetworkInfo, error)
	GetPeers(context.Context, *emptypb.Empty) (*GetPeersResponse, error)
	GetNodeHealth(context.Context, *emptypb.Empty) (*NodeHealth, error)
	// Consensus operations
	GetConsensusInfo(context.Context, *emptypb.Empty) (*ConsensusInfo, error)
	GetValidators(context.Context, *emptypb.Empty) (*GetValidatorsResponse, error)
	mustEmbedUnimplementedDiamanteBChainServiceServer()
}

// UnimplementedDiamanteBChainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiamanteBChainServiceServer struct{}

func (UnimplementedDiamanteBChainServiceServer) SubmitTransaction(context.Context, *SubmitTransactionRequest) (*SubmitTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTransaction not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) GetTransaction(context.Context, *GetTransactionRequest) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) GetTransactions(context.Context, *GetTransactionsRequest) (*GetTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactions not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) GetTransactionStatus(context.Context, *GetTransactionStatusRequest) (*TransactionStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionStatus not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) GetBlock(context.Context, *GetBlockRequest) (*Block, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlock not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) GetBlocks(context.Context, *GetBlocksRequest) (*GetBlocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlocks not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) GetLatestBlock(context.Context, *emptypb.Empty) (*Block, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestBlock not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) GetAccount(context.Context, *GetAccountRequest) (*Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) GetAccountBalance(context.Context, *GetAccountBalanceRequest) (*AccountBalance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountBalance not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) GetAccountTransactions(context.Context, *GetAccountTransactionsRequest) (*GetAccountTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountTransactions not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) CreateWallet(context.Context, *CreateWalletRequest) (*Wallet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWallet not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) GetWallet(context.Context, *GetWalletRequest) (*Wallet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWallet not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) SignTransaction(context.Context, *SignTransactionRequest) (*SignTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignTransaction not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) DeployContract(context.Context, *DeployContractRequest) (*DeployContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployContract not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) InvokeContract(context.Context, *InvokeContractRequest) (*InvokeContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeContract not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) GetContract(context.Context, *GetContractRequest) (*Contract, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContract not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) GetNetworkInfo(context.Context, *emptypb.Empty) (*NetworkInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNetworkInfo not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) GetPeers(context.Context, *emptypb.Empty) (*GetPeersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeers not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) GetNodeHealth(context.Context, *emptypb.Empty) (*NodeHealth, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeHealth not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) GetConsensusInfo(context.Context, *emptypb.Empty) (*ConsensusInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConsensusInfo not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) GetValidators(context.Context, *emptypb.Empty) (*GetValidatorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidators not implemented")
}
func (UnimplementedDiamanteBChainServiceServer) mustEmbedUnimplementedDiamanteBChainServiceServer() {}
func (UnimplementedDiamanteBChainServiceServer) testEmbeddedByValue()                               {}

// UnsafeDiamanteBChainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiamanteBChainServiceServer will
// result in compilation errors.
type UnsafeDiamanteBChainServiceServer interface {
	mustEmbedUnimplementedDiamanteBChainServiceServer()
}

func RegisterDiamanteBChainServiceServer(s grpc.ServiceRegistrar, srv DiamanteBChainServiceServer) {
	// If the following call pancis, it indicates UnimplementedDiamanteBChainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiamanteBChainService_ServiceDesc, srv)
}

func _DiamanteBChainService_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_SubmitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).SubmitTransaction(ctx, req.(*SubmitTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiamanteBChainService_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_GetTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiamanteBChainService_GetTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).GetTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_GetTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).GetTransactions(ctx, req.(*GetTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiamanteBChainService_GetTransactionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).GetTransactionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_GetTransactionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).GetTransactionStatus(ctx, req.(*GetTransactionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiamanteBChainService_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_GetBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiamanteBChainService_GetBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).GetBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_GetBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).GetBlocks(ctx, req.(*GetBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiamanteBChainService_GetLatestBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).GetLatestBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_GetLatestBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).GetLatestBlock(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiamanteBChainService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiamanteBChainService_GetAccountBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).GetAccountBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_GetAccountBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).GetAccountBalance(ctx, req.(*GetAccountBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiamanteBChainService_GetAccountTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).GetAccountTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_GetAccountTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).GetAccountTransactions(ctx, req.(*GetAccountTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiamanteBChainService_CreateWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).CreateWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_CreateWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).CreateWallet(ctx, req.(*CreateWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiamanteBChainService_GetWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).GetWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_GetWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).GetWallet(ctx, req.(*GetWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiamanteBChainService_SignTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).SignTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_SignTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).SignTransaction(ctx, req.(*SignTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiamanteBChainService_DeployContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).DeployContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_DeployContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).DeployContract(ctx, req.(*DeployContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiamanteBChainService_InvokeContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).InvokeContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_InvokeContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).InvokeContract(ctx, req.(*InvokeContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiamanteBChainService_GetContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).GetContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_GetContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).GetContract(ctx, req.(*GetContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiamanteBChainService_GetNetworkInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).GetNetworkInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_GetNetworkInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).GetNetworkInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiamanteBChainService_GetPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).GetPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_GetPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).GetPeers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiamanteBChainService_GetNodeHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).GetNodeHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_GetNodeHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).GetNodeHealth(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiamanteBChainService_GetConsensusInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).GetConsensusInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_GetConsensusInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).GetConsensusInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiamanteBChainService_GetValidators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiamanteBChainServiceServer).GetValidators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiamanteBChainService_GetValidators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiamanteBChainServiceServer).GetValidators(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DiamanteBChainService_ServiceDesc is the grpc.ServiceDesc for DiamanteBChainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiamanteBChainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "diamante.api.DiamanteBChainService",
	HandlerType: (*DiamanteBChainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTransaction",
			Handler:    _DiamanteBChainService_SubmitTransaction_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _DiamanteBChainService_GetTransaction_Handler,
		},
		{
			MethodName: "GetTransactions",
			Handler:    _DiamanteBChainService_GetTransactions_Handler,
		},
		{
			MethodName: "GetTransactionStatus",
			Handler:    _DiamanteBChainService_GetTransactionStatus_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _DiamanteBChainService_GetBlock_Handler,
		},
		{
			MethodName: "GetBlocks",
			Handler:    _DiamanteBChainService_GetBlocks_Handler,
		},
		{
			MethodName: "GetLatestBlock",
			Handler:    _DiamanteBChainService_GetLatestBlock_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _DiamanteBChainService_GetAccount_Handler,
		},
		{
			MethodName: "GetAccountBalance",
			Handler:    _DiamanteBChainService_GetAccountBalance_Handler,
		},
		{
			MethodName: "GetAccountTransactions",
			Handler:    _DiamanteBChainService_GetAccountTransactions_Handler,
		},
		{
			MethodName: "CreateWallet",
			Handler:    _DiamanteBChainService_CreateWallet_Handler,
		},
		{
			MethodName: "GetWallet",
			Handler:    _DiamanteBChainService_GetWallet_Handler,
		},
		{
			MethodName: "SignTransaction",
			Handler:    _DiamanteBChainService_SignTransaction_Handler,
		},
		{
			MethodName: "DeployContract",
			Handler:    _DiamanteBChainService_DeployContract_Handler,
		},
		{
			MethodName: "InvokeContract",
			Handler:    _DiamanteBChainService_InvokeContract_Handler,
		},
		{
			MethodName: "GetContract",
			Handler:    _DiamanteBChainService_GetContract_Handler,
		},
		{
			MethodName: "GetNetworkInfo",
			Handler:    _DiamanteBChainService_GetNetworkInfo_Handler,
		},
		{
			MethodName: "GetPeers",
			Handler:    _DiamanteBChainService_GetPeers_Handler,
		},
		{
			MethodName: "GetNodeHealth",
			Handler:    _DiamanteBChainService_GetNodeHealth_Handler,
		},
		{
			MethodName: "GetConsensusInfo",
			Handler:    _DiamanteBChainService_GetConsensusInfo_Handler,
		},
		{
			MethodName: "GetValidators",
			Handler:    _DiamanteBChainService_GetValidators_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/simple.proto",
}
